# Generated by Django 5.2.5 on 2025-08-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_qualifications_job_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
